In [ ]:
## Estadistica Aplicada 
Sesión 2 - 10 agosto

Francisco Javier Chavez Hernandez 2034204

Una lista en python es una colección de objetos que pueden ser de distinto tipo

#
alumno=['Francisco', 'Chavez', 21]

In [1]:
alumno=['Francisco', 'Chavez', 21]

In [2]:
type(alumno)

list

In [3]:
estadistica_g44=['Andrea', 'Ana','Carlos','Hugo']

In [4]:
#seleccion a Ana de la lista
estadistica_g44[1]

'Ana'

In [5]:
#seleccion a Carlos de la lista
estadistica_g44[2]

'Carlos'

In [10]:
#seleccion a Ana de la lista
estadistica_g44[0:2]

['Andrea', 'Ana']

In [11]:
estadistica_g44.append('Raul')

In [12]:
estadistica_g44

['Andrea', 'Ana', 'Carlos', 'Hugo', 'Raul']

In [13]:
estadistica_g44.remove('Hugo')

In [14]:
estadistica_g44


['Andrea', 'Ana', 'Carlos', 'Raul']

In [15]:
yo_enFCFM=['Francisco','LA', 85]

In [18]:
mi_promedio=yo_enFCFM[2]
mi_carrera=yo_enFCFM[1]

In [20]:
print('promedio:', mi_promedio, 'mi carrera:',mi_carrera)

promedio: 85 mi carrera: LA


## Librerias/paquetes/módulos
Una libreria en python es un conjunto de códigos que le indican a python cómo hacer determinadas cosas

Para usar una libreria:
1. Se instala
2. Se le indica a python que la utilice

In [ ]:
pip install yfinance

In [23]:
import yfinance as yf

In [ ]:
yf.download('US.MX', '')

## Numpy (numerical python)
Libreria que le sirve a python para manejar números
La estructura básica de numpy son los arreglos. Una coleccion de objetos del mismo tipo (numéricos)

Supongamos que tenemos la venta de aguas de la cafeteria de FCFM de la semana: Lunes 23, Martes 35, Miercoles 40, Jueves 28, Viernes 20

In [24]:
ventas=[23, 35, 40, 28, 20]

In [25]:
import numpy as np

In [26]:
#convertir la lista en un arreglo
ventas=np.array(ventas)

In [28]:
type(ventas)

numpy.ndarray

In [29]:
#suma
np.sum(ventas)

146

In [30]:
#multiplicacion
np.prod(ventas)

18032000

In [31]:
#valor maximo
np.max(ventas)

40

In [32]:
#valor minimo
np.min(ventas)

20

In [33]:
#promedio
np.mean(ventas)

29.2

In [34]:
#mediana
np.median(ventas)

28.0

In [36]:
#varianza
np.var(ventas)

54.96

In [37]:
#desviacion estandar
np.std(ventas)

7.413501197140255

In [38]:
# varianza muestral
np.var(ventas, ddof=1)

68.7

In [39]:
# desviacion estandar muestral
np.std(ventas, ddof=1)

8.28854631404084

In [40]:
#vector
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
#vector
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
#vector
np.arange(1,100, 15)

array([ 1, 16, 31, 46, 61, 76, 91])

In [43]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [44]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [45]:
np.full(6,8)

array([8, 8, 8, 8, 8, 8])

In [47]:
#Distribucion uniforme
np.random.randint(0,25,10)

array([15, 18,  6, 23, 17, 13,  5,  3,  9, 22])

In [48]:
#Fijar la semilla de la aleatoridad
np.random.seed(12)
#Distribucion uniforme
aleatorios=np.random.randint(0,25,10)

In [50]:
aleatorios=np.sort(aleatorios)

In [51]:
aleatorios

array([ 2,  3,  3,  6, 11, 12, 16, 17, 17, 22])

In [52]:
#contar los numeros aleatorios 
len(aleatorios)

10

In [54]:
np.random.seed(19)
aleatorios2=np.random.randint(0,25,9)

In [55]:
# generamos una lista
numeros=[2.45, 9.89, 12.4567]

1. Arreglo 2. media 3. redondear a dos decimales

In [59]:
#funcion
round(np.mean(np.array(numeros)),2)


8.27

In [60]:
#metodo
np.array(numeros).mean().round(2)

8.27